on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ released ]
    
jobs:
  nuget:
    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
  
  
  ## Remove old versions of packages form github NuGet feed
  nuget-delete-old-nuget-packages:
    name: "Delete Old NuGet"
    needs: [nuget]
    strategy:
      matrix:
        nuget-package: 
        - "Test-Package"
        - "Test-Package2"
    runs-on: ubuntu-latest
    
    steps:
    - name: Delete old NuGet packages
      uses: actions/delete-package-versions@v3
      with:
        owner: ${{ env.GITHUB_REPOSITORY_OWNER }}
        repo: ${{ github.event.repository.name }}
        token: ${{ secrets.GITHUB_TOKEN }}
        package-name: ${{ matrix.nuget-package }}
        min-versions-to-keep: 3
        
