on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  nuget:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: .NET 6.x SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
        
    - name: temp
      run: |
        echo "$env:GITHUB_REPOSITORY_OWNER"
        echo "https://nuget.pkg.github.com/$env:GITHUB_REPOSITORY_OWNER"


    #- name: Delete KubernetesClient old Package Versions
    #  uses: actions/delete-package-versions@v3
    #  with:
    #    owner: "$env:GITHUB_REPOSITORY_OWNER"
    #    repo: "https://nuget.pkg.github.com/$env:GITHUB_REPOSITORY_OWNER"
    #    package-name: "KubernetesClient"
    #    min-versions-to-keep: 10
    #    token: "${{ secrets.GITHUB_TOKEN }}"
