on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  nuget:
    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
  
  delete-old-packaged:
    strategy:
      matrix:
        nuget-package: ["Test-Package"]
    runs-on: ubuntu-latest
    
    steps:
    - name: .NET 6.x SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Delete old NuGet package versions
      uses: actions/delete-package-versions@v3
      with:
        owner: ${{ env.GITHUB_REPOSITORY_OWNER }}
        repo: "package-deletion-test"
        package-name: ${{ matrix.nuget-package }}
        min-versions-to-keep: 3
        token: "${{ secrets.GITHUB_TOKEN }}"
